# 03. Data Processing - Pandas

## 03.1. Importação das bibliotecas

### 03.1.1. Importando as bibliotecas nativas do Python

In [1]:
import sys

### 03.1.2. Importando as bibliotecas de terceiros

In [2]:
import pandas as pd
# from ydata_profiling import ProfileReport

### 03.1.3. Importando os módulos locais do projeto

In [3]:
sys.path.append('..')
import functions.fn_stats_pandas as fn_stats_pandas
import params.consts as consts

## 03.2. Visão geral dos dados

### 03.2.1. Habilitando a exibição de todas as colunas e linhas

In [4]:
pd.set_option('display.max_columns', None); pd.set_option('display.max_rows', None)

### 03.2.2. Armazenando o dataset em uma variável

In [5]:
df = pd.read_csv(consts.DATASET_RAW_COMPRESSED_PANDAS, compression = 'gzip')

### 03.2.3. Visualizando a quantidade de linhas e colunas do dataset

In [6]:
df.shape

(881666, 12)

### 03.2.4. Exibindo o dataset

In [7]:
df.head(5)

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

### 03.2.5. Visualizando os detalhes do dataset

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 881666 entries, 0 to 881665
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   CustomerID              881664 non-null  float64
 1   idade                   881664 non-null  float64
 2   sexo                    881664 non-null  object
 3   tempo_como_cliente      881663 non-null  float64
 4   frequencia_uso          881663 non-null  float64
 5   ligacoes_callcenter     881664 non-null  float64
 6   dias_atraso             881664 non-null  float64
 7   assinatura              881661 non-null  object
 8   duracao_contrato        881663 non-null  object
 9   total_gasto             881664 non-null  float64
 10  meses_ultima_interacao  881664 non-null  float64
 11  cancelou                881664 non-null  float64
dtypes: float64(9), object(3)
memory usage: 80.7+ MB

### 03.2.6. Visualizando as estatísticas das colunas numéricas

In [9]:
fn_stats_pandas.describe(df)

,CustomerID,idade,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,total_gasto,meses_ultima_interacao,cancelou
count,881664.00,881664.00,881663.00,881663.00,881664.00,881664.00,881664.00,881664.00,881664.00
mean,225398.67,39.37,31.26,15.81,3.60,12.97,631.62,14.48,0.57
std,129531.85,12.44,17.26,8.59,3.07,8.26,240.80,8.60,0.50
min,2.00,18.00,1.00,1.00,0.00,0.00,100.00,1.00,0.00
25%,113621.75,29.00,16.00,9.00,1.00,6.00,480.00,7.00,0.00
50%,226125.50,39.00,32.00,16.00,3.00,12.00,661.00,14.00,1.00
75%,337739.25,48.00,46.00,23.00,6.00,19.00,830.00,22.00,1.00
max,449999.00,65.00,60.00,30.00,10.00,30.00,1000.00,30.00,1.00

### 03.2.7. Visualizando as estatísticas da colunas categóricas

In [10]:
df.describe(exclude = 'number')

          sexo assinatura duracao_contrato
count   881664     881661           881663
unique       2          3                3
top       Male   Standard           Annual
freq    500504     298255           354396

### 03.2.8. Verificando os valores nulos das colunas

In [11]:
df.isnull().sum()

CustomerID                2
idade                     2
sexo                      2
tempo_como_cliente        3
frequencia_uso            3
ligacoes_callcenter       2
dias_atraso               2
assinatura                5
duracao_contrato          3
total_gasto               2
meses_ultima_interacao    2
cancelou                  2
dtype: int64

### 03.2.9. Verificando os valores distintos das colunas

In [12]:
df.nunique()

CustomerID                440832
idade                         48
sexo                           2
tempo_como_cliente            60
frequencia_uso                30
ligacoes_callcenter           11
dias_atraso                   31
assinatura                     3
duracao_contrato               3
total_gasto                68363
meses_ultima_interacao        30
cancelou                       2
dtype: int64

### 03.2.10. Verificando os registos totalmente duplicados

In [13]:
len(df) - len(df.drop_duplicates())

440828

### 03.2.11. Verificando a quantidade de colunas numéricas, categóricas e de data

In [14]:
num_cols = df.select_dtypes(include = 'number').shape[1]

categ_cols = df.select_dtypes(include = 'object').shape[1]

date_cols = df.select_dtypes(include = ['datetime64[ns]', 'datetime64[ns, UTC]']).shape[1]

print(f'- Numeric Columns: {num_cols}\n- Categoric Columns: {categ_cols}\n- Date Columns: {date_cols}')

- Numeric Columns: 9
- Categoric Columns: 3
- Date Columns: 0

## 03.3. Processamento dos dados

### 03.3.1. Removendo os registros totalmente duplicados

In [15]:
df = df.drop_duplicates()

### 03.3.2. Tratando as colunas com valores nulos/vazios

In [16]:
df = df.dropna()

### 03.3.3. Corrigindo os tipos de dados das colunas

- **N/A**

### 03.3.4. Criando colunas de tempo/idade

- **N/A**

### 03.3.5. Mesclando colunas com muitas categorias

- **N/A**

### 03.3.6. Unificando colunas semelhantes

- **N/A**

### 03.3.7. Criando colunas derivadas de outras

- **N/A**

### 03.3.8. Tratando as colunas com outliers

- **N/A**

### 03.3.9. Excluindo as colunas que contém valores únicos

In [17]:
df = df.drop('CustomerID', axis = 1)

### 03.3.10. Excluindo as colunas que contém valores constantes

- **N/A**

### 03.3.11. Excluindo as colunas que contém somente valores vazios

- **N/A**

### 03.3.12. Excluindo as colunas que contém muitos valores vazios

- **N/A**

### 03.3.13. Excluindo as colunas que contém informações redundantes

- **N/A**

### 03.3.14. Excluindo as colunas que contém informações irrelevantes

- **N/A**

### 03.3.15. Excluindo as colunas que contém textos livres

- **N/A**

### 03.3.16. Excluindo as colunas auxiliares

- **N/A**

### 03.3.17. Ordenando as colunas

In [18]:
df = df.reindex(columns = [
    'idade',
    'sexo',
    'total_gasto',
    'assinatura',
    'duracao_contrato',
    'tempo_como_cliente',
    'frequencia_uso',
    'ligacoes_callcenter',
    'dias_atraso',
    'meses_ultima_interacao',
    'cancelou',
])

## 03.4. Exportação dos dados

### 03.4.1. Salvando o dataset clean em parquet e compactado em snappy

In [19]:
df.to_parquet(

    consts.DATASET_CLEAN_PANDAS,

    index = False,

    compression = 'snappy'
    
)

### 03.4.2. Gerando um novo relatório Profile Report

In [20]:
# report_eda = ProfileReport(df)

# report_eda.to_file(consts.EDA_1)